export const fName = [
    "Spice", "Golden", "Urban", "Royal", "Red", "Green", "Blue", "Crimson", "Ocean", "Silver",
    "Smoky", "Sunny", "Rustic", "Hidden", "Velvet", "Wild", "Savory", "Sweet", "Flaming", "Amber",
    "Twisted", "Broken", "Flying", "Magic", "Crispy", "Epic", "Tandoori", "Bold", "Dragon", "Cozy",
    "Cracked", "Glowing", "Fat", "Lazy", "Grand", "Honey", "Little", "Midnight", "Neon", "Shiny",
    "Sticky", "Burning", "Fancy", "Fresh", "Sizzling", "Crazy", "Tender", "Wicked", "Zesty", "Noble"
];

export const sName = [
    "Fork", "Spoon", "Bistro", "Kitchen", "Oven", "Table", "Plate", "Feast", "Skillet", "Bowl",
    "Grill", "Garden", "Chop", "Ladle", "Pantry", "Tandoor", "Flame", "Belly", "Bar", "House",
    "Den", "Diner", "Corner", "Palate", "Tavern", "Nook", "Nest", "Place", "Zone", "Café",
    "Sizzle", "Pit", "Room", "Studio", "Flavors", "Lounge", "Wok", "Cellar", "Spot", "Counter",
    "Emporium", "Hub", "Hideout", "Taste", "Deck", "Commons", "Barn", "Crust", "Butcher", "Pan"
];

export const location = [
    "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai",
    "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Surat",
    "Lucknow", "Kanpur", "Nagpur", "Indore", "Bhopal",
    "Patna", "Ranchi", "Raipur", "Chandigarh", "Dehradun",
    "Shimla", "Manali", "Leh", "Srinagar", "Amritsar",
    "Agra", "Varanasi", "Allahabad", "Udaipur", "Jodhpur",
    "Guwahati", "Shillong", "Aizawl", "Imphal", "Kohima",
    "Panaji", "Thiruvananthapuram", "Kochi", "Madurai", "Coimbatore",
    "Tirupati", "Vijayawada", "Visakhapatnam", "Mysore", "Hubli",
    "Ludhiana", "Nashik", "Vadodara", "Gwalior", "Haridwar" 
]

export const reviewsWithRating = [
  { message: "Amazing food and great service!", rating: 5 },
  { message: "Decent experience, could be better.", rating: 3 },
  { message: "Loved the ambiance and the food!", rating: 5 },
  { message: "Not worth the price.", rating: 2 },
  { message: "Service was slow but food was good.", rating: 3 },
  { message: "Best dining experience I've had in a while!", rating: 5 },
  { message: "Mediocre at best.", rating: 2 },
  { message: "Great flavors, friendly staff.", rating: 4 },
  { message: "Too noisy, couldn't enjoy my meal.", rating: 2 },
  { message: "Absolutely delicious!", rating: 5 },
  { message: "Food was cold when served.", rating: 1 },
  { message: "Very hospitable staff.", rating: 4 },
  { message: "The place was packed but worth the wait.", rating: 4 },
  { message: "Undercooked meat, not returning.", rating: 1 },
  { message: "My kids loved the food.", rating: 4 },
  { message: "Prices are too high for the quality.", rating: 2 },
  { message: "Perfectly cooked and seasoned.", rating: 5 },
  { message: "Staff was inattentive.", rating: 2 },
  { message: "Good portion sizes.", rating: 4 },
  { message: "Average food, nice atmosphere.", rating: 3 },
  { message: "Wait time was excessive.", rating: 2 },
  { message: "The desserts were incredible.", rating: 5 },
  { message: "Nothing special, wouldn’t recommend.", rating: 2 },
  { message: "Friendly service, cozy spot.", rating: 4 },
  { message: "Everything was bland.", rating: 1 },
  { message: "Highly recommended!", rating: 5 },
  { message: "Great for families.", rating: 4 },
  { message: "Found hair in my food.", rating: 1 },
  { message: "Best pasta I've ever had.", rating: 5 },
  { message: "Clean place and good vibes.", rating: 4 },
  { message: "They forgot our order.", rating: 1 },
  { message: "Affordable and delicious.", rating: 4 },
  { message: "Nothing memorable.", rating: 3 },
  { message: "Tastes homemade and fresh.", rating: 5 },
  { message: "Slow service but friendly staff.", rating: 3 },
  { message: "The steak was perfect.", rating: 5 },
  { message: "Not enough vegetarian options.", rating: 2 },
  { message: "Very generous portions.", rating: 4 },
  { message: "The soup was salty.", rating: 2 },
  { message: "Nice decor, decent food.", rating: 3 },
  { message: "Will definitely come back.", rating: 5 },
  { message: "They messed up the bill.", rating: 1 },
  { message: "Comfort food at its best.", rating: 4 },
  { message: "Too crowded and noisy.", rating: 2 },
  { message: "Great spot for brunch!", rating: 5 },
  { message: "Wasn't impressed.", rating: 2 },
  { message: "Super fast service.", rating: 4 },
  { message: "They ran out of menu items.", rating: 1 },
  { message: "Delicious appetizers.", rating: 5 },
  { message: "Staff was very helpful.", rating: 4 },
  { message: "Overcooked and dry food.", rating: 1 },
  { message: "Nice view, average food.", rating: 3 },
  { message: "Presentation was top-notch.", rating: 5 },
  { message: "Very limited menu.", rating: 2 },
  { message: "Great value for money.", rating: 5 },
  { message: "The music was too loud.", rating: 2 },
  { message: "We were seated quickly.", rating: 4 },
  { message: "The food took forever.", rating: 1 },
  { message: "Everything was fresh and tasty.", rating: 5 },
  { message: "Friendly but forgetful waiters.", rating: 3 },
  { message: "The drinks were amazing.", rating: 4 },
  { message: "We had a great time.", rating: 5 },
  { message: "Wouldn’t return.", rating: 1 },
  { message: "Enjoyed every bite.", rating: 5 },
  { message: "Too pricey for what you get.", rating: 2 },
  { message: "My favorite local spot.", rating: 5 },
  { message: "The fish was undercooked.", rating: 1 },
  { message: "Service was okay.", rating: 3 },
  { message: "Loved the vibe.", rating: 4 },
  { message: "It was fine.", rating: 3 },
  { message: "Waiters were rude.", rating: 1 },
  { message: "Perfect date night location.", rating: 5 },
  { message: "I expected better.", rating: 2 },
  { message: "Excellent flavors.", rating: 5 },
  { message: "Won’t be coming back.", rating: 1 },
  { message: "Very satisfying meal.", rating: 4 },
  { message: "They were out of desserts.", rating: 2 },
  { message: "Best burger ever!", rating: 5 },
  { message: "Just average.", rating: 3 },
  { message: "Nice quiet place to relax.", rating: 4 },
  { message: "Long wait time.", rating: 2 },
  { message: "Perfect service.", rating: 5 },
  { message: "Okay-ish.", rating: 3 },
  { message: "Loved the unique dishes.", rating: 5 },
  { message: "Needs improvement.", rating: 2 },
  { message: "Family-friendly place.", rating: 4 },
  { message: "Chef knows what he’s doing!", rating: 5 },
  { message: "Not clean.", rating: 1 },
  { message: "Everything tasted the same.", rating: 2 },
  { message: "The sides were great.", rating: 4 },
  { message: "We got a free dessert!", rating: 5 },
  { message: "Did not enjoy it.", rating: 1 },
  { message: "Incredible place!", rating: 5 },
  { message: "Too salty.", rating: 2 },
  { message: "Perfect for a quick bite.", rating: 4 },
  { message: "Boring menu.", rating: 2 },
  { message: "A+ experience.", rating: 5 },
  { message: "Slow and sloppy.", rating: 1 },
  { message: "Really enjoyed it!", rating: 4 },
  { message: "Super cozy and warm.", rating: 5 },
  { message: "Cold food.", rating: 1 },
];


export const menuItems = ["Butter Chicken", "Paneer Butter Masala", "Chicken Biryani", "Mutton Rogan Josh", "Masala Dosa", "Plain Dosa", "Idli", "Medu Vada", "Sambar", "Vada Pav", "Pav Bhaji", "Chole Bhature", "Rajma Chawal", "Aloo Paratha", "Palak Paneer", "Dal Makhani", "Tandoori Chicken", "Chicken Tikka", "Fish Curry", "Prawn Masala", "Baingan Bharta", "Kadhi Pakora", "Malai Kofta", "Shahi Paneer", "Korma", "Naan", "Garlic Naan", "Tandoori Roti", "Poori", "Chapati", "Bhindi Masala", "Aloo Gobi", "Dum Aloo", "Veg Kolhapuri", "Veg Jalfrezi", "Gobi Manchurian", "Veg Pulao", "Jeera Rice", "Lemon Rice", "Tamarind Rice", "Curd Rice", "Litti Chokha", "Bisi Bele Bath", "Pesarattu", "Upma", "Khichdi", "Pongal", "Dhokla", "Khandvi", "Thepla", "Undhiyu", "Handvo", "Bhel Puri", "Pani Puri", "Sev Puri", "Ragda Pattice", "Aloo Tikki", "Chana Chaat", "Samosa", "Pakora", "Onion Bhaji", "Bread Pakora", "Momos", "Thukpa", "Chow Mein", "Chicken 65", "Chicken Chettinad", "Chicken Rezala", "Egg Curry", "Anda Bhurji", "Macher Jhol", "Sarson Da Saag", "Makki Di Roti", "Nihari", "Keema Matar", "Haleem", "Paya Soup", "Appam with Stew", "Neer Dosa", "Kerala Sadya", "Avial", "Banana Chips", "Misal Pav", "Sabudana Khichdi", "Poha", "Sheera", "Halwa", "Jalebi", "Gulab Jamun", "Rasgulla", "Sandesh", "Kheer", "Phirni", "Kulfi", "Falooda", "Modak", "Ladoo", "Barfi", "Peda"];

export const images=[
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864024/14_jscz2s.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/12_l7yokv.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864024/8_zcepvm.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864024/13_zwaemg.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/10_woc9ot.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/11_omt84d.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/5_jkizjh.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/9_v1neda.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/7_ng9qjl.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/6_h2p6lz.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/4_zevqtp.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864022/2_tqgrks.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864022/0_c1ohmd.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864022/3_vewnvo.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864022/1_lji5en.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864563/exterior-view-building_305343-42088_hpllfi.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864610/360_F_202146408_lJIlhogmEkLWLQUWScU9zPdKWrgpIE1u_vkpxy9.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864611/cafe-brick-walls-green-canopy-260nw-386619214_z2iykx.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751890204/360_F_668380954_3krhgtwcZr7nGROtEYJgzdQgOkd20APK_zomycl.webp",

]