export const fName = [
    "Spice", "Golden", "Urban", "Royal", "Red", "Green", "Blue", "Crimson", "Ocean", "Silver",
    "Smoky", "Sunny", "Rustic", "Hidden", "Velvet", "Wild", "Savory", "Sweet", "Flaming", "Amber",
    "Twisted", "Broken", "Flying", "Magic", "Crispy", "Epic", "Tandoori", "Bold", "Dragon", "Cozy",
    "Cracked", "Glowing", "Fat", "Lazy", "Grand", "Honey", "Little", "Midnight", "Neon", "Shiny",
    "Sticky", "Burning", "Fancy", "Fresh", "Sizzling", "Crazy", "Tender", "Wicked", "Zesty", "Noble"
];

export const sName = [
    "Fork", "Spoon", "Bistro", "Kitchen", "Oven", "Table", "Plate", "Feast", "Skillet", "Bowl",
    "Grill", "Garden", "Chop", "Ladle", "Pantry", "Tandoor", "Flame", "Belly", "Bar", "House",
    "Den", "Diner", "Corner", "Palate", "Tavern", "Nook", "Nest", "Place", "Zone", "Café",
    "Sizzle", "Pit", "Room", "Studio", "Flavors", "Lounge", "Wok", "Cellar", "Spot", "Counter",
    "Emporium", "Hub", "Hideout", "Taste", "Deck", "Commons", "Barn", "Crust", "Butcher", "Pan"
];

export const location = [
    "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai",
    "Kolkata", "Pune", "Ahmedabad", "Jaipur", "Surat",
    "Lucknow", "Kanpur", "Nagpur", "Indore", "Bhopal",
    "Patna", "Ranchi", "Raipur", "Chandigarh", "Dehradun",
    "Shimla", "Manali", "Leh", "Srinagar", "Amritsar",
    "Agra", "Varanasi", "Allahabad", "Udaipur", "Jodhpur",
    "Guwahati", "Shillong", "Aizawl", "Imphal", "Kohima",
    "Panaji", "Thiruvananthapuram", "Kochi", "Madurai", "Coimbatore",
    "Tirupati", "Vijayawada", "Visakhapatnam", "Mysore", "Hubli",
    "Ludhiana", "Nashik", "Vadodara", "Gwalior", "Haridwar" 
]

export const reviewsWithRating = [
  { message: "Amazing food and great service!", rating: 5 },
  { message: "Decent experience, could be better.", rating: 3 },
  { message: "Loved the ambiance and the food!", rating: 5 },
  { message: "Not worth the price.", rating: 2 },
  { message: "Service was slow but food was good.", rating: 3 },
  { message: "Best dining experience I've had in a while!", rating: 5 },
  { message: "Mediocre at best.", rating: 2 },
  { message: "Great flavors, friendly staff.", rating: 4 },
  { message: "Too noisy, couldn't enjoy my meal.", rating: 2 },
  { message: "Absolutely delicious!", rating: 5 },
  { message: "Food was cold when served.", rating: 1 },
  { message: "Very hospitable staff.", rating: 4 },
  { message: "The place was packed but worth the wait.", rating: 4 },
  { message: "Undercooked meat, not returning.", rating: 1 },
  { message: "My kids loved the food.", rating: 4 },
  { message: "Prices are too high for the quality.", rating: 2 },
  { message: "Perfectly cooked and seasoned.", rating: 5 },
  { message: "Staff was inattentive.", rating: 2 },
  { message: "Good portion sizes.", rating: 4 },
  { message: "Average food, nice atmosphere.", rating: 3 },
  { message: "Wait time was excessive.", rating: 2 },
  { message: "The desserts were incredible.", rating: 5 },
  { message: "Nothing special, wouldn't recommend.", rating: 2 },
  { message: "Friendly service, cozy spot.", rating: 4 },
  { message: "Everything was bland.", rating: 1 },
  { message: "Highly recommended!", rating: 5 },
  { message: "Great for families.", rating: 4 },
  { message: "Found hair in my food.", rating: 1 },
  { message: "Best pasta I've ever had.", rating: 5 },
  { message: "Clean place and good vibes.", rating: 4 },
  { message: "They forgot our order.", rating: 1 },
  { message: "Affordable and delicious.", rating: 4 },
  { message: "Nothing memorable.", rating: 3 },
  { message: "Tastes homemade and fresh.", rating: 5 },
  { message: "Slow service but friendly staff.", rating: 3 },
  { message: "The steak was perfect.", rating: 5 },
  { message: "Not enough vegetarian options.", rating: 2 },
  { message: "Very generous portions.", rating: 4 },
  { message: "The soup was salty.", rating: 2 },
  { message: "Nice decor, decent food.", rating: 3 },
  { message: "Will definitely come back.", rating: 5 },
  { message: "They messed up the bill.", rating: 1 },
  { message: "Comfort food at its best.", rating: 4 },
  { message: "Too crowded and noisy.", rating: 2 },
  { message: "Great spot for brunch!", rating: 5 },
  { message: "Wasn't impressed.", rating: 2 },
  { message: "Super fast service.", rating: 4 },
  { message: "They ran out of menu items.", rating: 1 },
  { message: "Delicious appetizers.", rating: 5 },
  { message: "Staff was very helpful.", rating: 4 },
  { message: "Overcooked and dry food.", rating: 1 },
  { message: "Nice view, average food.", rating: 3 },
  { message: "Presentation was top-notch.", rating: 5 },
  { message: "Very limited menu.", rating: 2 },
  { message: "Great value for money.", rating: 5 },
  { message: "The music was too loud.", rating: 2 },
  { message: "We were seated quickly.", rating: 4 },
  { message: "The food took forever.", rating: 1 },
  { message: "Everything was fresh and tasty.", rating: 5 },
  { message: "Friendly but forgetful waiters.", rating: 3 },
  { message: "The drinks were amazing.", rating: 4 },
  { message: "We had a great time.", rating: 5 },
  { message: "Wouldn't return.", rating: 1 },
  { message: "Enjoyed every bite.", rating: 5 },
  { message: "Too pricey for what you get.", rating: 2 },
  { message: "My favorite local spot.", rating: 5 },
  { message: "The fish was undercooked.", rating: 1 },
  { message: "Service was okay.", rating: 3 },
  { message: "Loved the vibe.", rating: 4 },
  { message: "It was fine.", rating: 3 },
  { message: "Waiters were rude.", rating: 1 },
  { message: "Perfect date night location.", rating: 5 },
  { message: "I expected better.", rating: 2 },
  { message: "Excellent flavors.", rating: 5 },
  { message: "Won't be coming back.", rating: 1 },
  { message: "Very satisfying meal.", rating: 4 },
  { message: "They were out of desserts.", rating: 2 },
  { message: "Best burger ever!", rating: 5 },
  { message: "Just average.", rating: 3 },
  { message: "Nice quiet place to relax.", rating: 4 },
  { message: "Long wait time.", rating: 2 },
  { message: "Perfect service.", rating: 5 },
  { message: "Okay-ish.", rating: 3 },
  { message: "Loved the unique dishes.", rating: 5 },
  { message: "Needs improvement.", rating: 2 },
  { message: "Family-friendly place.", rating: 4 },
  { message: "Chef knows what he's doing!", rating: 5 },
  { message: "Not clean.", rating: 1 },
  { message: "Everything tasted the same.", rating: 2 },
  { message: "The sides were great.", rating: 4 },
  { message: "We got a free dessert!", rating: 5 },
  { message: "Did not enjoy it.", rating: 1 },
  { message: "Incredible place!", rating: 5 },
  { message: "Too salty.", rating: 2 },
  { message: "Perfect for a quick bite.", rating: 4 },
  { message: "Boring menu.", rating: 2 },
  { message: "A+ experience.", rating: 5 },
  { message: "Slow and sloppy.", rating: 1 },
  { message: "Really enjoyed it!", rating: 4 },
  { message: "Super cozy and warm.", rating: 5 },
  { message: "Cold food.", rating: 1 },
];

export const descriptions= [
    "This is a casual dining spot blending rustic charm with modern flavors. Known for its farm-to-table philosophy, the menu highlights seasonal produce sourced directly from nearby farms. Guests enjoy wood-grilled steaks, artisan flatbreads, and hand-crafted cocktails served in a cozy, industrial-inspired setting with exposed brick walls and warm lighting. Weekend brunches are popular, featuring house-made pastries and cold-brew coffee. The place caters to both families and young professionals, offering vegetarian and gluten-free options. Its mission is simple: create honest food with bold flavors while supporting local agriculture and sustainable practices that bring the community together.",
    "A neighborhood gem tucked away on a quiet street, this bistro offers European comfort food with a modern twist. The menu ranges from creamy mushroom risotto and roasted duck to innovative seafood pastas prepared daily. The ambiance is intimate, with dim lantern lighting and soft acoustic music. Regulars praise the attentive staff, curated wine list, and warm desserts like chocolate lava cake. With an open kitchen concept, diners can watch chefs craft meals with precision. It is ideal for date nights, family gatherings, or small celebrations, making every visit feel personal, memorable, and full of charm.",
    "Specializing in slow-cooked barbecue traditions from across the American South, this spot smokes brisket, ribs, and pulled pork over hickory and oak wood until tender perfection. Side dishes like cornbread, mac-and-cheese, and collard greens round out hearty meals. The interior channels a rustic lodge with reclaimed wood tables and vintage signage, while upbeat country rock fills the space. Craft beers on tap highlight local breweries. Families, sports fans, and meat lovers flock here for generous portions, friendly service, and that unforgettable smoky aroma that greets you the moment you walk in through the front door.",
    "A vibrant, plant-forward space celebrating Asian-inspired vegetarian cuisine, this café features sesame tofu bowls, Thai basil noodles, and miso-glazed eggplant that showcase bold flavors without meat. Eco-friendly packaging and compostable utensils align with its sustainable ethos. Bright murals of lotus flowers decorate the dining space, complemented by hanging greenery and bamboo furnishings. Smooth jazz and the aroma of herbal teas create a calming environment. Guests appreciate the affordable lunch specials and vegan desserts, especially the matcha cheesecake. It proves vegetarian dining can be both flavorful and fulfilling, attracting students, professionals, and families in equal measure.",
    "Offering diners a relaxed coastal experience even miles away from the ocean, this spot centers its menu on fresh seafood classics. Buttery lobster rolls, grilled salmon with citrus glaze, and fish tacos topped with tangy slaw headline the offerings. Nautical décor, including seashell chandeliers and boat-inspired booths, reinforces the seaside theme. The bar serves tropical cocktails like piña coladas and mojitos, perfect for warm evenings. Families love the kids' menu, while adults enjoy oyster happy hours on Fridays. It combines casual charm with quality ingredients, making it a go-to destination for seafood cravings and laid-back summer vibes.",
    "A countryside-inspired retreat in the city, this tavern is famous for hearty meals and locally brewed beers. The menu features roasted chicken, shepherd's pie, and sizzling skillet platters served piping hot. Wooden beams, stone fireplaces, and antler chandeliers create a warm, rustic vibe reminiscent of a mountain lodge. On weekends, live folk bands entertain guests while they sip craft ales. The tavern caters to groups with generous portion sizes and shareable appetizers. Families, coworkers, and travelers find comfort in its inviting atmosphere. It feels like more than a restaurant — it's a gathering place rooted in hospitality.",
    "This lively kitchen celebrates global flavors with an eclectic menu that changes seasonally. Expect Moroccan tagines, Indian curries, and Middle Eastern mezze platters prepared with authentic spices. Bold colors and handcrafted lanterns decorate the dining room, creating an atmosphere reminiscent of a bustling spice market. The restaurant also hosts World Food Nights where guest chefs showcase international recipes. Specialty teas and Turkish coffee are customer favorites, pairing perfectly with baklava or saffron cake. The mix of exotic aromas, friendly servers, and lively energy transports diners beyond borders, making the experience feel like a culinary adventure across continents.",
    "A hybrid café and deli where artisanal coffee meets gourmet sandwiches, this space draws crowds from early morning to late evening. Breakfast brings fresh croissants, lattes, and smoothie bowls, while afternoons highlight stacked pastrami sandwiches, avocado wraps, and vibrant salads. The interior is cozy, with velvet seating, warm lighting, and chalkboard menus. Students and freelancers flock here for free Wi-Fi, while office workers grab quick yet high-quality lunches. Seasonal drinks like pumpkin spice cold brew or peppermint mochas keep regulars coming back. Its charm lies in balancing the sophistication of specialty coffee with the comfort of hearty meals.",
    "Perched above the city, this lounge offers panoramic views paired with upscale small plates and cocktails. As the sun sets, fairy lights twinkle above and a DJ curates smooth beats. The menu focuses on sharing — truffle fries, sliders, sushi rolls, and charcuterie boards. Signature drinks include fruit-infused martinis and craft gin mixes. The vibe is chic yet relaxed, attracting young professionals and couples seeking a stylish night out. Weekends bring live acoustic sets that complement the open-sky ambiance. The place balances urban sophistication with a playful, social spirit, making it one of the city's most Instagrammable destinations.",
    "A family-run bakery café known for warm breads, pastries, and comforting meals, this place always smells like sourdough, butter croissants, and cinnamon rolls fresh from the oven. Beyond baked goods, it serves soups, quiches, and sandwiches on house-made bread. Wooden shelves display jars of jam and artisanal honey for purchase. Customers enjoy sipping lattes while reading by the large windows. Staff greet regulars by name, making visits feel personal. With its old-world charm and recipes passed down through generations, it offers an inviting escape from busy life, where every bite carries the warmth of home-cooked tradition.",
    "This retro-inspired diner blends nostalgia with modern dining. Neon signs glow above red leather booths while a jukebox plays golden hits from the '60s. The menu features classics like fluffy pancakes, juicy burgers, and thick milkshakes served in frosted glasses. Night owls appreciate its late-night hours, making it a favorite for post-concert meals and midnight cravings. Friendly servers keep the coffee hot and the atmosphere lively. Families come for weekend brunch, while college students love the affordable combo meals. The diner's enduring charm lies in its ability to transport guests back to simpler times without sacrificing flavor or quality.",
    "A modern brasserie with a rustic twist, this space is designed with stone walls, wooden beams, and sleek copper accents. The menu highlights contemporary European cuisine — roasted lamb shank, seafood linguine, and artisan flatbreads baked in a wood-fired oven. An open kitchen lets diners watch chefs in action, while a carefully curated wine list complements each dish. Business professionals frequent it for power lunches, and couples come for romantic dinners by candlelight. Service is polished yet welcoming. The brasserie thrives on delivering high-quality meals with an emphasis on presentation, creating memorable experiences for those who value detail and flavor.",
    "This bustling eatery specializes in quick, flavorful meals inspired by global street food. Think Korean BBQ tacos, Mediterranean falafel wraps, and spicy Indian chaats — all crafted with fresh ingredients and served fast. The décor is vibrant, featuring graffiti art and neon signs that echo the energy of urban markets. A rotating specials board ensures there's always something new to try. Young crowds love the lively vibe, while families appreciate the variety. Prices are wallet-friendly, but quality remains high. The eatery captures the spirit of travel and discovery, offering a passport to world flavors without leaving the neighborhood.",
    "An upscale dining spot with a flair for drama, this restaurant focuses on bold flavors and artistic plating. Expect dishes like pan-seared duck breast with cherry glaze, saffron-infused risotto, and decadent chocolate soufflés. Deep red interiors, velvet drapes, and candlelit tables create an atmosphere of elegance. The service is attentive but unpretentious, making guests feel cared for. Sommeliers help pair wines from an extensive cellar, and mixologists craft cocktails with theatrical flair. It's a popular choice for anniversaries, proposals, and special celebrations. Every detail, from the plating to the playlist, works together to make dining a memorable event.",
    "This airy café is surrounded by greenery, offering an oasis of calm in the middle of the city. The menu focuses on light, refreshing dishes — avocado toast, quinoa salads, fresh-pressed juices, and herbal teas. Outdoor seating on a sunlit terrace is the highlight, with hanging plants and floral arrangements enhancing the garden feel. Inside, large windows bring in natural light, creating a bright, cheerful ambiance. It's a favorite for brunch lovers, freelancers with laptops, and friends catching up over coffee. With its mix of health-conscious food and relaxing atmosphere, it's a go-to spot for unwinding in style.",
]

export const menuItems = [
    "Butter Chicken", "Paneer Butter Masala", "Chicken Biryani", "Mutton Rogan Josh", "Masala Dosa", "Plain Dosa", "Idli", "Medu Vada", "Sambar", "Vada Pav", "Pav Bhaji", "Chole Bhature", "Rajma Chawal", "Aloo Paratha", "Palak Paneer", "Dal Makhani", "Tandoori Chicken", "Chicken Tikka", "Fish Curry", "Prawn Masala", "Baingan Bharta", "Kadhi Pakora", "Malai Kofta", "Shahi Paneer", "Korma", "Naan", "Garlic Naan", "Tandoori Roti", "Poori", "Chapati", "Bhindi Masala", "Aloo Gobi", "Dum Aloo", "Veg Kolhapuri", "Veg Jalfrezi", "Gobi Manchurian", "Veg Pulao", "Jeera Rice", "Lemon Rice", "Tamarind Rice", "Curd Rice", "Litti Chokha", "Bisi Bele Bath", "Pesarattu", "Upma", "Khichdi", "Pongal", "Dhokla", "Khandvi", "Thepla", "Undhiyu", "Handvo", "Bhel Puri", "Pani Puri", "Sev Puri", "Ragda Pattice", "Aloo Tikki", "Chana Chaat", "Samosa", "Pakora", "Onion Bhaji", "Bread Pakora", "Momos", "Thukpa", "Chow Mein", "Chicken 65", "Chicken Chettinad", "Chicken Rezala", "Egg Curry", "Anda Bhurji", "Macher Jhol", "Sarson Da Saag", "Makki Di Roti", "Nihari", "Keema Matar", "Haleem", "Paya Soup", "Appam with Stew", "Neer Dosa", "Kerala Sadya", "Avial", "Banana Chips", "Misal Pav", "Sabudana Khichdi", "Poha", "Sheera", "Halwa", "Jalebi", "Gulab Jamun", "Rasgulla", "Sandesh", "Kheer", "Phirni", "Kulfi", "Falooda", "Modak", "Ladoo", "Barfi", "Peda"
];

export const images=[
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864024/14_jscz2s.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/12_l7yokv.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864024/8_zcepvm.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864024/13_zwaemg.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/10_woc9ot.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/11_omt84d.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/5_jkizjh.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/9_v1neda.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/7_ng9qjl.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/6_h2p6lz.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864023/4_zevqtp.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864022/2_tqgrks.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864022/0_c1ohmd.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864022/3_vewnvo.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864022/1_lji5en.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864563/exterior-view-building_305343-42088_hpllfi.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864610/360_F_202146408_lJIlhogmEkLWLQUWScU9zPdKWrgpIE1u_vkpxy9.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751864611/cafe-brick-walls-green-canopy-260nw-386619214_z2iykx.webp",
    "https://res.cloudinary.com/dysk6v0ag/image/upload/v1751890204/360_F_668380954_3krhgtwcZr7nGROtEYJgzdQgOkd20APK_zomycl.webp",

]